version: "3.12"

services:
  crewai:
    build: .
    container_name: crewai-weather
    env_file:
      - .env
    command: python weather_crew.py
    volumes:
      - .:/app
    restart: always  # Ensures the service restarts if it fails

  fastapi:
    build:
      context: .
      dockerfile: Dockerfile.fastapi  # Ensure Dockerfile exists for FastAPI
    container_name: fastapi-weather
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - crewai  # FastAPI will start only after CrewAI is up
    restart: always
    command: uvicorn app:app --host 0.0.0.0 --port 8000 --reload

  streamlit:
    build:
      context: .
      dockerfile: Dockerfile.streamlit  # Ensure this exists
    container_name: streamlit-weather
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    depends_on:
      - crewai
      - fastapi  # Streamlit will start only after both CrewAI and FastAPI are running
    restart: always
    command: streamlit run streamlit_app.py --server.port=8501 --server.address=0.0.0.0
